config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos', to:'todos#index'
  get 'todos/new'
  get 'todos/list'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show'
  get 'todos/:id/edit', to: 'todos#edit'
  patch 'todos/:id', to: 'todos#update', as: :todo
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/completed', to: 'todos#completed'

  resources :todos
  root 'todos#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
validates :description ,presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :set_todo, only: [:show, :completed, :edit, :update, :destroy]


  def index
    @todos = Todo.all
  end


  def show

  end


  def new
    @todo = Todo.new
  end


  def edit

  end


  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
       if @todo.save
         format.html { redirect_to todos_url, notice: 'Todo creado.' }
         format.json { render :show, status: :created, location: @todo }
       else
         format.html { render :new }
         format.json { render json: @todo.errors, status: :unprocessable_entity }
       end
     end

  end



    def update

      @todo.update(todo_params)
      redirect_to todos_path
      end


      def completed

      end

      def list

        @todos = Todo.all


      end



  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  private

    def todo_params
      params.require(:todo).permit(:description, :completed)
    end


    def set_todo
      @todo = Todo.find(params[:id])
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


<script
			  src="https://code.jquery.com/jquery-3.3.1.js"
			  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
			  crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<nav class="navbar fixed-top navbar-light bg-light">

    <%= link_to 'Inicio', todos_path, class:'btn btn-success' %>
    <%= link_to 'Crear nuevo Todo', todos_new_path, class:'btn btn-success' %>
    <%= link_to 'Estados de Validación', todos_list_path, class:'btn btn-success' %>
  </nav>







  <div class="jumbotron">
      <h1 class="display-3">Todos</h1>

  <div class="well">

<%= form_with model: @todo, local: true do |f| %>

    <%= f.label :title, "Descripcion de todo" %>
    <%= f.text_field :description %>
    <div>
    <%= f.label :content, "Completed" %>
    <%= f.check_box :completed?%>
    </div>

    <%= f.submit "Enviar", class:'btn btn-success' %>



    <% end %>

  </div>
</div>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<nav class="navbar fixed-top navbar-light bg-light">

    <%= link_to 'Inicio', todos_path, class:'btn btn-success' %>
    <%= link_to 'Crear nuevo Todo', todos_new_path, class:'btn btn-success' %>
    <%= link_to 'Estados de Validación', todos_list_path, class:'btn btn-success' %>
  </nav>


<div class="jumbotron">
  <h1 class="display-3">Todos</h1>
</div>

    <% @todos.each do |todo| %>
    <div class="well">
    <div class="container">
        <div class="row">




            <div class="col-sm-4">
                <h5><strong>ID</strong></h5>
              <%=  todo.id %> </div>

                <div class="col-sm-4">
                    <h5><strong>Contenido</strong></h5>
                   <%=  todo.description %> </div>



                  <div class="col-sm-4">
                      <h5><strong>Validado</strong></h5>
                    <%=  todo.completed %> </div>

      <div>
        <%= link_to 'Mostrar', todo ,class:'btn btn-info'%>
        <%= link_to 'Edit', edit_todo_path(todo), class:'btn btn-primary' %>
        <%= link_to 'Borrar', todo, method: :delete, data: { confirm: 'Seguro?' },class:'btn btn-warning' %>

       </div>

      </div>

    </div>

  </div>
    <% end %>


      <div style="padding:2%">
    <%= link_to 'Crear nuevo Todo', todos_new_path, class:'btn btn-success' %>
      </div>

app/views/todos/list.html.erb
<nav class="navbar fixed-top navbar-light bg-light">

    <%= link_to 'Inicio', todos_path, class:'btn btn-success' %>
    <%= link_to 'Crear nuevo Todo', todos_new_path, class:'btn btn-success' %>
    <%= link_to 'Estados de Validación', todos_list_path, class:'btn btn-success' %>
  </nav>





......................
<div class="row" >
    <div class="col-md-6">
    <div class="container">


        <div class="container">
          <div class="jumbotron">
              <h1 class="display-3">Validados</h1>
            </div>



            <% @todos.each do |todo| %>
             <% if todo.completed == true %>

             <div class="well">
                <div class="container">
                    <div class="row">


                  <div class="col-sm-6">
                      <h5><strong>ID</strong></h5>
                    <%=  todo.id %> </div>

                      <div class="col-sm-6">
                          <h5><strong>Contenido</strong></h5>
                         <%=  todo.description %> </div>



                        <div class="col-sm-6">
                            <h5><strong>Validado</strong></h5>
                          <%=  todo.completed %> </div>

            <div>
              <%= link_to 'Mostrar', todo ,class:'btn btn-info'%>
              <%= link_to 'Edit', edit_todo_path(todo), class:'btn btn-primary' %>
              <%= link_to 'Borrar', todo, method: :delete, data: { confirm: 'Seguro?' },class:'btn btn-warning' %>

             </div>
             <% end %>
            </div>

          </div>

        </div>
          <% end %>

        </div>

      </div>
    </div>
</div>

    <div class="col-md-6">
    <div class="container">


          <div class="container">
            <div class="jumbotron">
                <h1 class="display-3"> No Validados</h1>
              </div>



              <% @todos.each do |todo| %>
               <% if todo.completed == false %>

               <div class="well">
                  <div class="container">
                      <div class="row">


                    <div class="col-sm-6">
                        <h5><strong>ID</strong></h5>
                      <%=  todo.id %> </div>

                        <div class="col-sm-6">
                            <h5><strong>Contenido</strong></h5>
                           <%=  todo.description %> </div>



                          <div class="col-sm-6">
                              <h5><strong>Validado</strong></h5>
                            <%=  todo.completed %> </div>

              <div>
                <%= link_to 'Mostrar', todo ,class:'btn btn-info'%>
                <%= link_to 'Edit', edit_todo_path(todo), class:'btn btn-primary' %>
                <%= link_to 'Borrar', todo, method: :delete, data: { confirm: 'Seguro?' },class:'btn btn-warning' %>

               </div>
               <% end %>
              </div>

            </div>

          </div>
            <% end %>

          </div>

        </div>
      </div>
    </div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h1><%= @todo.description %> </h1>
<p><%= @todo.completed %> </p>
<p><%= @todo.created_at%></p>
<div>
    <%= link_to 'Regresar', todos_path, class:'btn btn-success' %>
</div>